language: python
sudo: false
cache: pip
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    dist: xenial
    sudo: required
    env: TOXENV=py37
  - python: 3.8-dev
    env: TOXENV=py38

install:
  - pip install -r requirements.txt
  - pip install python_coveralls
script:
  - tox
after_success:
  - coveralls