sudo: false
language: python

matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7-dev
    env: TOXENV=py37

install:
  - pip install -r requirements.txt
  - pip install codecov python_coveralls
script:
  - tox
after_success:
  - codecov
  - coveralls