language: python
sudo: required
dist: xenial
python:
  - 3.6
  - 3.7
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    dist: xenial
    sudo: required
    env: TOXENV=py37

install:
  - pip install -r requirements.txt
  - pip install codecov python_coveralls
script:
  - tox
after_success:
  - codecov --token=822f86c3-65e2-40dd-b532-ee39861188d4
  - coveralls